# Generated by Django 5.2.6 on 2025-09-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Image',
            new_name='image',
        ),
    ]
